export const data = {
  products: [
    {
      name: "watch",
      url: "watch",
      caterogy: "accessary",
      image: "/images/p1.jpg",
      price: 100,
      countInStock: 10,
      brand: "Nike",
      rating: "4.5",
      description: "High Quality Watch",
    },
    {
      name: "watch",
      url: "watch",
      caterogy: "accessary",
      image: "/images/p1.jpg",
      price: 100,
      countInStock: 10,
      brand: "Nike",
      rating: "4.5",
      description: "High Quality Watch",
    },
    {
      name: "watch",
      url: "watch",
      caterogy: "accessary",
      image: "/images/p1.jpg",
      price: 100,
      countInStock: 10,
      brand: "Nike",
      rating: "4.5",
      description: "High Quality Watch",
    },
    {
      name: "watch",
      url: "watch",
      caterogy: "accessary",
      image: "/images/p1.jpg",
      price: 100,
      countInStock: 10,
      brand: "Nike",
      rating: "4.5",
      description: "High Quality Watch",
    },
  ],
};
